# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'home.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStackedWidget, QStatusBar,
    QTableWidget, QTableWidgetItem, QTextEdit, QWidget)
import icon_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setMaximumSize(QSize(800, 600))
        font = QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"")
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.action_1 = QAction(MainWindow)
        self.action_1.setObjectName(u"action_1")
        self.action_3 = QAction(MainWindow)
        self.action_3.setObjectName(u"action_3")
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        self.action_4 = QAction(MainWindow)
        self.action_4.setObjectName(u"action_4")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(0, 0, 141, 61))
        font1 = QFont()
        font1.setPointSize(11)
        self.pushButton.setFont(font1)
        self.pushButton.setStyleSheet(u"")
        icon = QIcon()
        icon.addFile(u":/icon/icon/\u9996\u9875_home.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(0, 120, 141, 61))
        self.pushButton_2.setFont(font1)
        self.pushButton_2.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u":/icon/icon/\u97f3\u9891\u6587\u4ef6_audio-file.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(0, 180, 141, 61))
        self.pushButton_3.setFont(font1)
        self.pushButton_3.setStyleSheet(u"")
        icon2 = QIcon()
        icon2.addFile(u":/icon/icon/\u7167\u7247_pic.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(0, 240, 141, 61))
        self.pushButton_4.setFont(font1)
        self.pushButton_4.setStyleSheet(u"")
        icon3 = QIcon()
        icon3.addFile(u":/icon/icon/\u538b\u7f29_compression.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_1 = QPushButton(self.centralwidget)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setGeometry(QRect(0, 60, 141, 61))
        self.pushButton_1.setFont(font1)
        self.pushButton_1.setStyleSheet(u"")
        icon4 = QIcon()
        icon4.addFile(u":/icon/icon/\u89c6\u9891_video-two.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_1.setIcon(icon4)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(140, 0, 651, 571))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.textEdit = QTextEdit(self.page)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, 0, 651, 561))
        self.stackedWidget.addWidget(self.page)
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.comboBox = QComboBox(self.page_1)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 10, 81, 31))
        self.label = QLabel(self.page_1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(275, 10, 90, 30))
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tableWidget = QTableWidget(self.page_1)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(-5, 61, 651, 421))
        self.pushButton_5 = QPushButton(self.page_1)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(530, 10, 111, 41))
        font2 = QFont()
        font2.setPointSize(10)
        self.pushButton_5.setFont(font2)
        icon5 = QIcon()
        icon5.addFile(u":/icon/icon/\u914d\u7f6e_config.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_6 = QPushButton(self.page_1)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(10, 500, 111, 41))
        self.pushButton_6.setFont(font2)
        icon6 = QIcon()
        icon6.addFile(u":/icon/icon/\u6587\u4ef6\u6dfb\u52a0_file-addition.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_7 = QPushButton(self.page_1)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(130, 500, 111, 41))
        self.pushButton_7.setFont(font2)
        icon7 = QIcon()
        icon7.addFile(u":/icon/icon/\u79fb\u9664_close.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_8 = QPushButton(self.page_1)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(250, 500, 111, 41))
        self.pushButton_8.setFont(font2)
        icon8 = QIcon()
        icon8.addFile(u":/icon/icon/\u6e05\u9664_clear.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_8.setIcon(icon8)
        self.pushButton_9 = QPushButton(self.page_1)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(530, 500, 111, 41))
        self.pushButton_9.setFont(font2)
        icon9 = QIcon()
        icon9.addFile(u":/icon/icon/\u786e\u5b9a_check.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_9.setIcon(icon9)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_2 = QLabel(self.page_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(275, 10, 90, 30))
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBox_2 = QComboBox(self.page_2)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(10, 10, 81, 31))
        self.pushButton_10 = QPushButton(self.page_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(530, 10, 111, 41))
        self.pushButton_10.setFont(font2)
        self.pushButton_10.setIcon(icon5)
        self.tableWidget_2 = QTableWidget(self.page_2)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(-5, 61, 651, 421))
        self.pushButton_11 = QPushButton(self.page_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(10, 500, 111, 41))
        self.pushButton_11.setFont(font2)
        self.pushButton_11.setIcon(icon6)
        self.pushButton_12 = QPushButton(self.page_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(130, 500, 111, 41))
        self.pushButton_12.setFont(font2)
        self.pushButton_12.setIcon(icon7)
        self.pushButton_13 = QPushButton(self.page_2)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(250, 500, 111, 41))
        self.pushButton_13.setFont(font2)
        self.pushButton_13.setIcon(icon8)
        self.pushButton_14 = QPushButton(self.page_2)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(530, 500, 111, 41))
        self.pushButton_14.setFont(font2)
        self.pushButton_14.setIcon(icon9)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_3 = QLabel(self.page_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(275, 10, 90, 30))
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBox_3 = QComboBox(self.page_3)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(10, 10, 81, 31))
        self.pushButton_15 = QPushButton(self.page_3)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(530, 10, 111, 41))
        self.pushButton_15.setFont(font2)
        self.pushButton_15.setIcon(icon5)
        self.tableWidget_3 = QTableWidget(self.page_3)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(-5, 61, 651, 421))
        self.pushButton_16 = QPushButton(self.page_3)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(10, 500, 111, 41))
        self.pushButton_16.setFont(font2)
        self.pushButton_16.setIcon(icon6)
        self.pushButton_17 = QPushButton(self.page_3)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(130, 500, 111, 41))
        self.pushButton_17.setFont(font2)
        self.pushButton_17.setIcon(icon7)
        self.pushButton_18 = QPushButton(self.page_3)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(250, 500, 111, 41))
        self.pushButton_18.setFont(font2)
        self.pushButton_18.setIcon(icon8)
        self.pushButton_19 = QPushButton(self.page_3)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(530, 500, 111, 41))
        self.pushButton_19.setFont(font2)
        self.pushButton_19.setIcon(icon9)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.pushButton_20 = QPushButton(self.page_4)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(10, 10, 111, 41))
        self.pushButton_20.setFont(font2)
        self.pushButton_20.setIcon(icon6)
        self.pushButton_21 = QPushButton(self.page_4)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(130, 10, 111, 41))
        self.pushButton_21.setFont(font2)
        self.pushButton_21.setIcon(icon7)
        self.pushButton_22 = QPushButton(self.page_4)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(250, 10, 111, 41))
        self.pushButton_22.setFont(font2)
        self.pushButton_22.setIcon(icon8)
        self.pushButton_23 = QPushButton(self.page_4)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(530, 10, 111, 41))
        self.pushButton_23.setFont(font2)
        self.pushButton_23.setIcon(icon9)
        self.tableWidget_4 = QTableWidget(self.page_4)
        self.tableWidget_4.setObjectName(u"tableWidget_4")
        self.tableWidget_4.setGeometry(QRect(-5, 61, 471, 481))
        self.label_4 = QLabel(self.page_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(470, 100, 71, 31))
        self.label_4.setFont(font2)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBox_4 = QComboBox(self.page_4)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(375, 10, 90, 41))
        self.label_5 = QLabel(self.page_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(470, 170, 71, 31))
        self.label_5.setFont(font2)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.page_4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(470, 240, 71, 31))
        self.label_6.setFont(font2)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.page_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(470, 310, 71, 31))
        self.label_7.setFont(font2)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit = QLineEdit(self.page_4)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(550, 170, 81, 31))
        self.lineEdit.setMaxLength(2)
        self.lineEdit_1 = QLineEdit(self.page_4)
        self.lineEdit_1.setObjectName(u"lineEdit_1")
        self.lineEdit_1.setGeometry(QRect(550, 240, 81, 31))
        self.lineEdit_1.setMaxLength(4)
        self.lineEdit_2 = QLineEdit(self.page_4)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(550, 310, 81, 31))
        self.lineEdit_2.setMaxLength(4)
        self.comboBox_5 = QComboBox(self.page_4)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(550, 100, 81, 31))
        self.stackedWidget.addWidget(self.page_4)
        self.pushButton_24 = QPushButton(self.centralwidget)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(0, 300, 141, 61))
        self.pushButton_24.setFont(font1)
        self.pushButton_24.setStyleSheet(u"")
        self.pushButton_24.setIcon(icon3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 23))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_1)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu.addSeparator()

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Open\u683c\u5f0f\u8f6c\u6362", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u62a4\u773c\u7eff", None))
        self.action_1.setText(QCoreApplication.translate("MainWindow", u"\u674f\u4ec1\u9ec4", None))
        self.action_3.setText(QCoreApplication.translate("MainWindow", u"\u77f3\u9752\u7070", None))
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u6de1\u84dd\u68a6\u5e7b", None))
        self.action_4.setText(QCoreApplication.translate("MainWindow", u"\u73cd\u73e0\u767d", None))
#if QT_CONFIG(tooltip)
        self.pushButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u7a0b\u5e8f\u9996\u9875</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u9996\u9875", None))
#if QT_CONFIG(tooltip)
        self.pushButton_2.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u97f3\u9891\u683c\u5f0f\u8f6c\u6362</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891", None))
#if QT_CONFIG(tooltip)
        self.pushButton_3.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u56fe\u7247\u683c\u5f0f\u8f6c\u6362</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247", None))
#if QT_CONFIG(tooltip)
        self.pushButton_4.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u89c6\u9891\u538b\u7f29</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u538b\u7f29", None))
#if QT_CONFIG(tooltip)
        self.pushButton_1.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u89c6\u9891\u683c\u5f0f\u8f6c\u6362</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_1.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891", None))
        self.textEdit.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Open\u683c\u5f0f\u8f6c\u6362 v1.1</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">\u9879"
                        "\u76ee\u7b80\u4ecb</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Open Format Conversion \u662f\u4e00\u6b3e\u4e13\u4e3a Linux \u7cfb\u7edf\u5f00\u53d1 \u7684 \u56fe\u5f62\u5316\u683c\u5f0f\u8f6c\u6362\u5de5\u5177\uff0c\u65e8\u5728\u4e3a\u7528\u6237\u63d0\u4f9b\u539f\u751f\u3001\u9ad8\u6548\u4e14\u5f00\u6e90\u7684Linux\u683c\u5f0f\u8f6c\u6362\u89e3\u51b3\u65b9\u6848\u3002\u9879\u76ee\u7075\u611f\u6e90\u81ea Deepin \u8bba\u575b\u7f51\u53cb\u9700\u6c42\u2014\u2014\u6253\u9020\u4e00\u4e2a Linux \u539f\u751f GUI \u4ea4\u4e92 \u7684\u5f00\u6e90\u7a0b\u5e8f\u3002</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11"
                        "pt;\">\u8bbf\u95ee\u5730\u5740</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">\u5b98\u65b9\u7f51\u7ad9\uff1a</span><a href=\"https://mrarub.eu.org\"><span style=\" text-decoration: underline; color:#0000ff;\">https://mrarub.eu.org</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">\u4ee3\u7801\u4ed3\u5e93\uff1a</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">GitHub\uff08\u56fd\u9645\uff09\uff1a</span><a href=\"https://github.com/mrarub/Open-Format-Conversion\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/mrarub/Open-Format-Conversion</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; mar"
                        "gin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Gitee\uff08\u56fd\u5185\u52a0\u901f\uff09\uff1a</span><a href=\"https://gitee.com/mrarub/Open-Format-Conversion\"><span style=\" text-decoration: underline; color:#0000ff;\">https://gitee.com/mrarub/Open-Format-Conversion</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u2606\u652f\u6301\u4e0e\u9f13\u52b1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u5982\u679c Open Format Conversion \u5bf9\u60a8\u6709\u6240\u5e2e\u52a9\uff0c\u6b22\u8fce\u70b9\u51fb\u53f3\u4e0a\u89d2\u7684 \u2606 Star \u4e3a\u9879\u76ee\u70b9\u4eae\u5c0f\u661f\u661f\uff5e</p>\n"
"<p style=\" margin-top:0px; mar"
                        "gin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u60a8\u7684\u652f\u6301\u662f\u6211\u6301\u7eed\u4f18\u5316\u7684\u6700\u5927\u52a8\u529b\uff01\u2606</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\uff08\u6ce8\uff1a\u53ef\u5728 GitHub/Gitee \u4ed3\u5e93\u9875\u9762\u53f3\u4e0a\u89d2\u627e\u5230\u661f\u661f\u56fe\u6807\u54e6\uff5e\uff09</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">\u6280\u672f\u6808</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">\u9879\u76ee\u4f7f\u7528\u4e86\u4ee5\u4e0b\u5f00\u6e90"
                        "\u9879\u76ee\uff1a</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">PySide6\uff1a</span><a href=\"https://code.qt.io/cgit/pyside\"><span style=\" text-decoration: underline; color:#0000ff;\">https://code.qt.io/cgit/pyside</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">FFmpeg\uff1a</span><a href=\"https://github.com/FFmpeg/FFmpeg\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/FFmpeg/FFmpeg</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">onnxruntime\uff1a</span><a href=\"https://github.com/microsoft/onnxruntime\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/microsoft/onnxruntime</s"
                        "pan></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">U-2-Net\uff1a</span><a href=\"https://github.com/xuebinqin/U-2-Net\u200b\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/xuebinqin/U-2-Net\u200b</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Real-ESRGAN\uff1a</span><a href=\"https://github.com/xinntao/Real-ESRGAN\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/xinntao/Real-ESRGAN</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pillow<span style=\" font-size:10pt;\">\uff1a</span><a href=\"https://github.com/xinntao/Real-ESRGAN\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/python-"
                        "pillow/Pillow</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">PyInstaller\uff1a</span><a href=\"https://github.com/pyinstaller/pyinstaller\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/pyinstaller/pyinstaller</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">\u8d21\u732e\u4e0e\u53cd\u9988</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">\u6b22\u8fce\u901a\u8fc7 GitHub/Gitee \u63d0\u4ea4 Issue \u6216 Pull Request \u53c2"
                        "\u4e0e\u9879\u76ee\u6539\u8fdb\uff01</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">\u5982\u9700\u5e2e\u52a9\u6216\u53cd\u9988\u95ee\u9898\uff0c\u53ef\u901a\u8fc7\u5b98\u65b9\u7f51\u7ad9\u6216\u4ed3\u5e93 Issues \u8054\u7cfb\u5f00\u53d1\u8005\u3002</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">\u66f4\u65b0\u65e5\u5fd7:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">0.9 \u7b2c\u4e00\u4e2a\u53d1\u884c\u7248\u672c</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; marg"
                        "in-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">0.9.1 \u4fee\u590d\u95ee\u9898:\u89c6\u9891\u538b\u7f29\u53c2\u6570\u4e0d\u751f\u6548\u95ee\u9898\u3002</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">           \u589e\u52a0\u529f\u80fd:\u8f6c\u6362\u6267\u884c\u5b8c\uff0c\u70b9\u51fb\u5b8c\u6210\u81ea\u52a8\u6253\u5f00\u8f93\u51fa\u76ee\u5f55</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.9.2 <span style=\" font-size:10pt;\">\u589e\u52a0\u529f\u80fd:\u5728\u521b\u5efa\u65b0\u4efb\u52a1\u524d\u589e\u52a0\u72b6\u6001\u6821\u9a8c\u903b\u8f91\uff0c\u5f53\u68c0\u6d4b\u5230\u5b58\u5728\u6b63\u5728\u8fd0\u884c\u4efb\u52a1\u65f6\uff0c\u963b\u65ad\u65b0\u4efb\u52a1\u542f\u52a8\u5e76\u89e6\u53d1\u53cb\u597d\u63d0\u793a\u673a\u5236</span></p>\n"
"<p style=\" "
                        "margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">0.9.3 \u4fee\u590d\u95ee\u9898:\u4efb\u52a1\u6267\u884c\u5b8c\u6210\u540e\uff0c\u8f93\u51fa\u76ee\u5f55\u7684\u6253\u5f00\u903b\u8f91\u7531 &quot;\u6839\u636e\u505c\u7559\u9875\u9762&quot; \u8c03\u6574\u4e3a &quot;\u6839\u636e\u5b9e\u9645\u6267\u884c\u7684\u4efb\u52a1&quot;<br />1.0 \u589e\u52a0\u529f\u80fd:\u300c\u4e3b\u9898\u76ae\u80a4\u989c\u8272\u8c03\u8282\u300d\u529f\u80fd\uff0c\u652f\u6301\u4e2a\u6027\u5316\u8bbe\u7f6e\uff0c\u6253\u9020\u4e13\u5c5e\u754c\u9762\u98ce\u683c</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">       \u7a0b\u5e8f\u4f18\u5316:\u7cbe\u7b80\u7a0b\u5e8f\u4ee3\u7801\u7ed3\u6784\uff0c\u79fb\u9664\u5197\u4f59\u4e0e\u65e0\u7528\u4ee3\u7801</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-rig"
                        "ht:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">                          \u7a0b\u5e8f\u754c\u9762\u5e03\u5c40\u8c03\u6574\u4e3a\u300c\u56fa\u5b9a\u6a21\u5f0f\u300d\uff0c\u589e\u5f3a\u4f7f\u7528\u7a33\u5b9a\u6027\uff0c\u5fae\u8c03\u7a0b\u5e8fUI\u754c\u9762</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">1.1 \u589e\u52a0\u529f\u80fd:\u4e00\u952e\u62a0\u56fe\uff1a\u667a\u80fd\u5206\u5272\u4e3b\u4f53\u4e0e\u80cc\u666f\uff0c\u652f\u6301\u591a\u7c7b\u578b\u56fe\u50cf\u200b</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">                          \u80cc\u666f\u66f4\u6362\uff1a\u652f\u6301\u66f4\u6362\u80cc\u666f\u989c\u8272</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-ind"
                        "ent:0px;\"><span style=\" font-size:10pt;\">                          \u56fe\u7247\u6e05\u6670\u5316\uff1a\u6df1\u5ea6\u5b66\u4e60\u589e\u5f3a\u7ec6\u8282\uff0c\u4f18\u5316\u753b\u8d28</span></p></body></html>", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"MP4", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"MKV", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"MOV", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"AVI", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"GIF", None))

        self.label.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u683c\u5f0f\u8f6c\u6362", None))
#if QT_CONFIG(tooltip)
        self.pushButton_5.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u8fd9\u662f\u9ad8\u7ea7\u914d\u7f6e\uff0c\u9700\u8981\u6709\u57fa\u7840\u7684\u4e86\u89e3</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u9ad8\u7ea7\u914d\u7f6e", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6587\u4ef6", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u9664", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u9664\u5168\u90e8", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\u6267\u884c", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891\u683c\u5f0f\u8f6c\u6362", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"MP3", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"AAC", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"FLAC", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("MainWindow", u"M4A", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("MainWindow", u"WAV", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("MainWindow", u"OGG", None))
        self.comboBox_2.setItemText(6, QCoreApplication.translate("MainWindow", u"AC3", None))
        self.comboBox_2.setItemText(7, QCoreApplication.translate("MainWindow", u"WMA", None))
        self.comboBox_2.setItemText(8, QCoreApplication.translate("MainWindow", u"MP2", None))
        self.comboBox_2.setItemText(9, QCoreApplication.translate("MainWindow", u"WV", None))

#if QT_CONFIG(tooltip)
        self.pushButton_10.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u8fd9\u662f\u9ad8\u7ea7\u914d\u7f6e\uff0c\u9700\u8981\u6709\u57fa\u7840\u7684\u4e86\u89e3</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"\u9ad8\u7ea7\u914d\u7f6e", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6587\u4ef6", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u9664", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u9664\u5168\u90e8", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"\u6267\u884c", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u683c\u5f0f\u8f6c\u6362", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", u"JPG", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", u"PNG", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("MainWindow", u"WEBP", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("MainWindow", u"BMP", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("MainWindow", u"TIFF", None))
        self.comboBox_3.setItemText(5, QCoreApplication.translate("MainWindow", u"JPEG", None))
        self.comboBox_3.setItemText(6, QCoreApplication.translate("MainWindow", u"ICO", None))

#if QT_CONFIG(tooltip)
        self.pushButton_15.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u8fd9\u662f\u9ad8\u7ea7\u914d\u7f6e\uff0c\u9700\u8981\u6709\u57fa\u7840\u7684\u4e86\u89e3</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"\u9ad8\u7ea7\u914d\u7f6e", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6587\u4ef6", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u9664", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u9664\u5168\u90e8", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"\u6267\u884c", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6587\u4ef6", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u9664", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u9664\u5168\u90e8", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"\u6267\u884c", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u7f16\u7801\u5668", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", u"MP4", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"MOV", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", u"MKV", None))
        self.comboBox_4.setItemText(3, QCoreApplication.translate("MainWindow", u"AVI", None))

        self.label_5.setText(QCoreApplication.translate("MainWindow", u"CRF", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u5bbd\u5ea6", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u9ad8\u5ea6", None))
#if QT_CONFIG(tooltip)
        self.lineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>CRF\u662f\u538b\u7f29\u7b49\u7ea7\uff0c\u4e00\u822c\u9ed8\u8ba4\u5373\u53ef\u3002\u53ea\u53ef\u586b\u51990-51\u8303\u56f4(\u4e00\u822c\u6700\u597d\u572820-35\u5185)\u3002\u6570\u5b57\u8d8a\u9ad8\u538b\u7f29\u8d8a\u5c0f</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"23", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("MainWindow", u"libx264", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("MainWindow", u"libx265", None))

#if QT_CONFIG(tooltip)
        self.comboBox_5.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u8fd9\u662f\u89c6\u9891\u7f16\u7801\u5668\uff0c\u4e00\u822c\u9ed8\u8ba4\u5373\u53ef\u3002libx264\u517c\u5bb9\u6027\u597d\uff0c\u5904\u7406\u901f\u5ea6\u5feb\u3002libx265\u538b\u7f29\u7a0b\u5e8f\u66f4\u597d\uff0c\u901f\u5ea6\u7565\u6162</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.pushButton_24.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u4e00\u952e\u62a0\u56fe\uff0c\u66f4\u6362\u80cc\u666f\uff0c\u56fe\u7247\u9ad8\u6e05\u5904\u7406</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u5904\u7406", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u76ae\u80a4", None))
    # retranslateUi

